In [55]:
import numpy as np

In [56]:
Input_file = open('Day 10 Input')
Input = []
for line in Input_file:
    Input.append(line.strip())

In [57]:
cycle_counter = 1
cycle_boolean = 0
X_value = 1
Important_X = []

def cycle_checker(x):
    if x == 20 or x == 60 or x == 100 or x == 140 or x == 180 or x == 220:
        boolean = 1
    else:
        boolean = 0
    
    return boolean

for i in Input:
    if i[0] == 'n':
        if cycle_checker(cycle_counter) == 1:
            Important_X.append(X_value * cycle_counter)
        cycle_counter = cycle_counter + 1
    if i[0] == 'a':
        if cycle_checker(cycle_counter) == 1:
            Important_X.append(X_value * cycle_counter)
        cycle_counter = cycle_counter + 1
 
        if cycle_checker(cycle_counter) == 1:
            Important_X.append(X_value * cycle_counter)
        X_value = X_value + int(i[5:])
        cycle_counter = cycle_counter + 1
            
Sum = 0
for i in Important_X:
    Sum = Sum + i
print(Sum)

12460


In [59]:
Screen = np.ones((1,240))
cycle_counter = 0
X_value = 1

def pixel_check(x, cycle):
    multiple = 0
    for j in np.arange(5):
        if cycle >= 40:
            cycle = cycle - 40
            multiple = multiple + 1
    
    if np.abs(x - cycle) < 2:
        Screen[0][cycle + (40 * multiple)] = 0
    return

for i in Input:
    if i[0] == 'n':
        pixel_check(X_value, cycle_counter)
        
        cycle_counter = cycle_counter + 1
        
        
    if i[0] == 'a':
        pixel_check(X_value, cycle_counter)
        cycle_counter = cycle_counter + 1
        pixel_check(X_value, cycle_counter)
        X_value = X_value + int(i[5:])
        cycle_counter = cycle_counter + 1
        
Screen = Screen.reshape((6,40))
np.set_printoptions(linewidth=np.inf)
print(Screen)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 1. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 0. 1.]]
